### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by shroffk** [ChannelFinder/recsync#70]
@mdavidsaver @tynanford can we tag the master branch as a new release.

I think a release is justified given the expanded support for info tags

**Comment by tynanford** [comment]
Makes sense to me. Looks like a lot of changes since the last release
- Support for non-linux targets - OSX, RTEMS (4.9, 4.10, 5.7), and Windows
- New `addReccasterEnvVars` iocsh function for reccaster
- `RSRV_SERVER_PORT` and `PVAS_SERVER_PORT` sent by default in reccaster
- Added sending recordDesc (.DESC) in reccaster and recordDesc toggle in recceiver
- New `environment_vars` configuration parameter in recceiver

https://github.com/ChannelFinder/recsync/compare/1.4...master

**Comment by shroffk** [comment]
Ok,
I already did a release of ChannelFinder services 4.7.1 so it might also be good to release recsync too and announce both release together

**Comment by shroffk** [comment]
Done
